# Generated by Django 4.1.6 on 2023-02-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_ciudad_estudiante_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.CharField(default='si', max_length=25)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
            ],
        ),
    ]
