# Generated by Django 4.1.6 on 2023-02-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='aprobado',
            field=models.IntegerField(choices=[(1, 'si'), (2, 'no')], default=1),
        ),
    ]
