# Generated by Django 4.1.6 on 2023-02-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_resultado_aprobado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='aprobado',
            new_name='desercion',
        ),
    ]
